spring:
   datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/login?characterEncoding=utf-8&useSSL=false
      diver-class-name: com.mysql.jdbc.Driver

      
   redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:

   mvc:    favicon:      enabled: false


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 999
      logic-not-delete-value: 000    